# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

# ignore warning
inhibit_all_warnings!

target 'FriendCircleDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

#######YYKit#######
pod 'YYKit'
pod 'SDWebImage'
pod 'IQKeyboardManager'
pod 'Masonry'
pod 'YYKeyboardManager'    

  # Pods for FriendCircleDemo

  target 'FriendCircleDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FriendCircleDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
